#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# flashcards
# Copyright (c) 2020 Hugh Coleman
#
# This file is part of hughcoleman/flashcards, a flashcard quiz for the 
# command line. It is released under the MIT License (see LICENSE.)

import argparse
import math

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("-n", "--number", default=math.inf, type=int,
            help="number of questions to ask")
    parser.add_argument("-r", "--repetitions", default=math.inf, type=int,
            help="maximum number of times each question can be asked")
    parser.add_argument("-l", "--linear", action="store_true",
            help="do not shuffle questions")

    parser.add_argument("questions", type=argparse.FileType("r"),
            help="tsv of questions to ask")

    args = parser.parse_args()

    i = 0
    while i < args.number:
        print("Question #{}: {}".format(i + 1, ""))
        i = i + 1
